apiVersion: v1
kind: PersistentVolume
metadata:
  name: opspv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 172.17.211.42
    path: /data/k8s

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opspvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harborpv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 172.17.211.42
    path: /data/harbor

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harborpvc
  namespace: kube-ops
spec: 
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi

