---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-jenkins3
  namespace: kube-ops
spec:
  rules:
  - host: jenkins3.tydicdev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins4
          servicePort: 8080

