---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-jenkins
  namespace: kube-ops
spec:
  rules:
  - host: jenkins.tydicdev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins2
          servicePort: 8080

