apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tomcat-pod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat-pod
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5-jre8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  annotations:
    traefik.ingress.kubernetes.io/load-balancer-method: drr
spec:
  template:
    metadata:
      labels:
        name: tomcat-service
        namespace: default
spec:
  selector:
    app: tomcat-pod
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: tomcat.tydicdev.com
    http:
      paths:
      - path: /tomcat/
        backend:
          serviceName: tomcat-service
          servicePort: 80
      - path: /nginx/
        backend:
          serviceName: nginx-service
          servicePort: 80
